# Generated by Django 4.0.4 on 2022-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='mail',
            field=models.EmailField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='mobile_num',
            field=models.IntegerField(),
        ),
    ]
